* Аптечка для путешествий
Гражданин без специального образования имеет право оказывать только первую доврачебную помощь и должен обратиться к специалистам при первой же возможности. Вы не имеете права назначать и вводить препараты кому-либо другому. Все манипуляции с лекарством без наличия согласия другого человека будут находиться за правовым полем. Поэтому если вы даете какие-либо препараты из аптечки другому человеку, он должен принять их самостоятельно и добровольно.

Состав личной аптечки:
- персональные лекарства от хронических заболеваний;
- лекарства от заболеваний, которые чаще всего случаются (например, средство от головной боли);
- пластырь и бинт;
- эластичный бинт.

Состав групповой аптечки:
- сердечно-сосудистые средства;
- желудочно-кишечные средства;
- обезболивающие и противовоспалительные средства;
- противопростудные средства;
- антибиотики, антисептики и противовирусные средства;
- противоаллергические средства;
- средства, применяемые при заболевании органов дыхания;
- средства для обработки ран, ушибов, ожогов.

В собранной групповой аптечке должен быть список всех содержащихся медикаментов с указаниями по применению.

* Распространенные проблемы со здоровьем в путешествиях
** Пищевые отравления
Для предупреждения отравления необходимо употреблять в пищу только доброкачественные продукты и кипятить питьевую воду.

При симптомах отравления принимают абсорбирующие препараты (активированный уголь и его аналоги) или, в худшем случае, промывают желудок.

** Солнечный или тепловой удар
Для профилактики необходимо защищать голову от солнца светлым головным убором или платком. Не рекомендуется совершать большие переходы в жаркие часы дня.

Пострадавшего переносят в тень и смачивают голову холодной водой. Голова пострадавшего должна быть приподнята.

** Ожог
По глубине поражения ткани ожоги делятся на 4 степени. При небольших ожогах 1-2 степени (покраснения, волдыри) на пораженное место накладывают повязку, которая поможет избежать контакта с внешней средой. При необходимости пораженное место обрабатывается мазью от ожогов. При серьезных ожогах 3-4 степени пострадавшего срочно транспортируют в ближайший мед. пункт, допустима лишь стерильная повязка.

Оказывая первую помощь при ожогах нельзя:
- отдирать приставшую к обожженной коже одежду (ее следует обрезать вокруг);
- вскрывать пузыри на коже;
- смазывать места ожога жиром или маслом.

** Переохлаждение
При оказании первой помощи обеспечивают отдых, уменьшение физической нагрузки и согревание (костер, теплая одежда, горячий чай или кофе).

** Обморожение
Возникает в результате действий на организм человека холода или низких температур. Различают 4 степени обморожения:
- 1-я степень. Участок обморожения темнеет, теряет чувствительность. После отогревания участок краснеет, припухает.
- 2-я степень. Участок обморожения резко темнеет. После отогревания багровеет, появляются пузыри со светлой или кровянистой жидкостью.
- 3-я степень. Омертвление кожи.
- 4-я степень. Омертвление кожи, мягких тканей и костей.

При появлении первых признаков обморожения необходимо немедленно растереть побелевшее место. До покраснения кожи, восстановления чувствительности пострадавшего доставляют в теплое помещение, делают ему легкий массаж, а сам он должен активно двигать отмороженными частями тела. Рекомендуется отогревание в теплой воде с повышением температуры от 18 до 35-40 градусов. На обмороженный участок накладывают сухую стерильную повязку, одновременно пострадавшему дают горячий чай.

На морозе следует следить за носом, ушами, щеками, чтобы сразу обнаружить обморожение и принять меры.

** Ссадины и раны
Ссадины и раны промывают раствором хлоргиксидина, загрязненные раны — перекисью водорода. Кожу вокруг обрабатывают йодом или аналогами и закрывают повязкой, иногда заклеивают медицинским клеем БФ-6 при необходимости.

** Кровотечение
Артерию необходимо прижать пальцем, согнуть и поднять раненную конечность, наложить давящую повязку (жгут или закрутку из подручных средств) на раненную конечность. Жгут накладывается поверх одежды или на валик из ваты марли выше места ранения, но по возможности ближе к ране. Жгут не должен слишком сильно сдавливать конечность и оставаться на ней не более полутора часов.

** Ушибы, растяжения и разрывы связок
Признаки растяжений и разрывов связок:
- резкая боль в области сустава;
- кровоизлияние;
- отек тканей.

В первые часы после травмы применяют холод и фиксирующую повязку.

** Вывихи
При вывихе нарушается правильное соотношение суставных концов костей. Не следует самостоятельно вправлять сустав. Рекомендуется наложить шину как при переломе, применить болеутоляющие средства и обратиться в мед. пункт.

** Переломы
При закрытых переломах кожа остается неповрежденной, а при открытой бывают разрывы мягких тканей и обломки костей нередко торчат из раны.

При закрытом переломе на поврежденную поверхность накладывают шину. Сделать ее можно из фанеры, палок, прутьев и других подручных средств поверх одежды. Шиной охватывают суставы выше и ниже поврежденной кости. Если нет подручного материала для шины, то надо придать неподвижность поврежденной конечности, прибинтовав ее к здоровой (ногу к ноге, руку в согнутом положении прибинтовывают к туловищу).

При открытом переломе костей прежде всего останавливают кровотечение, делают перевязку, а затем накладывают на поврежденную конечность шину.

** Укусы насекомых
Укусы комаров, мошки, слепни вызывают раздражения кожи, иногда аллергические реакции. Для защиты от насекомых чаще всего применяют репелленты, отпугивающие вещества.

При укусах клеща необходимо обратиться в поликлинику, поскольку клещи — переносчики опасных заболеваний.

** Укусы змей
При укусе ядовитой змеи необходимо наложить жгут выше места укуса и доставить пострадавшего в больницу.
