* Аптечка для путешествий
Гражданин без специального образования имеет право оказывать только первую доврачебную помощь и должен обратиться к специалистам при первой же возможности. Вы не имеете права назначать и вводить препараты кому-либо другому. Все манипуляции с лекарством без наличия согласия другого человека будут находиться за правовым полем. Поэтому если вы даете какие-либо препараты из аптечки другому человеку, он должен принять их самостоятельно и добровольно.

Состав личной аптечки:
- персональные лекарства от хронических заболеваний;
- лекарства от заболеваний, которые чаще всего случаются (например, средство от головной боли);
- пластырь и бинт;
- эластичный бинт.

Состав групповой аптечки:
- сердечно-сосудистые средства;
- желудочно-кишечные средства;
- обезболивающие и противовоспалительные средства;
- противопростудные средства;
- антибиотики, антисептики и противовирусные средства;
- противоаллергические средства;
- средства, применяемые при заболевании органов дыхания;
- средства для обработки ран, ушибов, ожогов.

В собранной групповой аптечке должен быть список всех содержащихся медикаментов с указаниями по применению.

* Распространенные проблемы со здоровьем в путешествиях
** Пищевые отравления
Для предупреждения отравления необходимо употреблять в пищу только доброкачественные продукты и кипятить питьевую воду.

При симптомах отравления принимают абсорбирующие препараты (активированный уголь и его аналоги) или, в худшем случае, промывают желудок.

** Солнечный или тепловой удар
Для профилактики необходимо защищать голову от солнца светлым головным убором или платком. Не рекомендуется совершать большие переходы в жаркие часы дня.

Пострадавшего переносят в тень и смачивают голову холодной водой. Голова пострадавшего должна быть приподнята.

** Ожог
По глубине поражения ткани ожоги делятся на 4 степени. При небольших ожогах 1-2 степени (покраснения, волдыри) на пораженное место накладывают повязку, которая поможет избежать контакта с внешней средой. При необходимости пораженное место обрабатывается мазью от ожогов. При серьезных ожогах 3-4 степени пострадавшего срочно транспортируют в ближайший мед. пункт, допустима лишь стерильная повязка.

Оказывая первую помощь при ожогах нельзя:
- отдирать приставшую к обожженной коже одежду (ее следует обрезать вокруг);
- вскрывать пузыри на коже;
- смазывать места ожога жиром или маслом.

** Переохлаждение
При оказании первой помощи обеспечивают отдых, уменьшение физической нагрузки и согревание (костер, теплая одежда, горячий чай или кофе).

** Обморожение
Возникает в результате действий на организм человека холода или низких температур. Различают 4 степени обморожения:
- 1-я степень. Участок обморожения темнеет, теряет чувствительность. После отогревания участок краснеет, припухает.

Не забыть перед поездкой:
- установить нужные приложения на смартфон;
- узнать правила поведения в стране;
- разделить деньги и документы на части;
- сделать прививки.
- 2-я степень. Участок обморожения резко темнеет. После отогревания багровеет, появляются пузыри со светлой или кровянистой жидкостью.
- 3-я степень. Омертвление кожи.
- 4-я степень. Омертвление кожи, мягких тканей и костей.

При появлении первых признаков обморожения необходимо немедленно растереть побелевшее место. До покраснения кожи, восстановления чувствительности пострадавшего доставляют в теплое помещение, делают ему легкий массаж, а сам он должен активно двигать отмороженными частями тела. Рекомендуется отогревание в теплой воде с повышением температуры от 18 до 35-40 градусов. На обмороженный участок накладывают сухую стерильную повязку, одновременно пострадавшему дают горячий чай.

На морозе следует следить за носом, ушами, щеками, чтобы сразу обнаружить обморожение и принять меры.

** Ссадины и раны
Ссадины и раны промывают раствором хлоргиксидина, загрязненные раны — перекисью водорода. Кожу вокруг обрабатывают йодом или аналогами и закрывают повязкой, иногда заклеивают медицинским клеем БФ-6 при необходимости.

** Кровотечение
Артерию необходимо прижать пальцем, согнуть и поднять раненную конечность, наложить давящую повязку (жгут или закрутку из подручных средств) на раненную конечность. Жгут накладывается поверх одежды или на валик из ваты марли выше места ранения, но по возможности ближе к ране. Жгут не должен слишком сильно сдавливать конечность и оставаться на ней не более полутора часов.

** Ушибы, растяжения и разрывы связок
Признаки растяжений и разрывов связок:
- резкая боль в области сустава;
- кровоизлияние;
- отек тканей.

В первые часы после травмы применяют холод и фиксирующую повязку.

** Вывихи
При вывихе нарушается правильное соотношение суставных концов костей. Не следует самостоятельно вправлять сустав. Рекомендуется наложить шину как при переломе, применить болеутоляющие средства и обратиться в мед. пункт.

** Переломы
При закрытых переломах кожа остается неповрежденной, а при открытой бывают разрывы мягких тканей и обломки костей нередко торчат из раны.

При закрытом переломе на поврежденную поверхность накладывают шину. Сделать ее можно из фанеры, палок, прутьев и других подручных средств поверх одежды. Шиной охватывают суставы выше и ниже поврежденной кости. Если нет подручного материала для шины, то надо придать неподвижность поврежденной конечности, прибинтовав ее к здоровой (ногу к ноге, руку в согнутом положении прибинтовывают к туловищу).

При открытом переломе костей прежде всего останавливают кровотечение, делают перевязку, а затем накладывают на поврежденную конечность шину.

** Укусы насекомых
Укусы комаров, мошки, слепни вызывают раздражения кожи, иногда аллергические реакции. Для защиты от насекомых чаще всего применяют репелленты, отпугивающие вещества.

При укусах клеща необходимо обратиться в поликлинику, поскольку клещи — переносчики опасных заболеваний.

** Укусы змей
При укусе ядовитой змеи необходимо наложить жгут выше места укуса и доставить пострадавшего в больницу.

* Страхование жизни и здоровья
** Основные термины
Страхователь (выгодоприобретатель, застрахованный) — юридическое лицо или дееспособное физическое лицо, заключившее со страховщиками договор страхования, либо являющиеся страхователями в силу закона.

Страховщик (страховая компания) — это организация, с которой заключается договор, которая оплачивает лечение и другие расходы по страховому случаю.

Страховой случай — это неблагоприятное событие, предусмотренное договором, в связи с которым страховщик выплатит возмещение.

Страховая сумма — это максимальная сумма, которую выплатит страховая компания. Эта сумма включает в себя расходы на больницу, транспорт и т. д.

Ассистанс — это сервисная компания, помощник застрахованного. Их работа — вызов скорой, поиск больницы, организация транспорта и т. д.

** Страхование от несчастного случая
Предназначено для возмещения ущерба, вызванного потерей здоровья или смертью застрахованного. Выплата совершается в процентном отношении от страховой суммы в соответствии с таблицей выплат. Можно оформлять и для путешествий по России, и для путешествий за рубежом.

** Страхование выезжающих за рубеж
Обеспечивает защиту от ущерба имущества, жизни, здоровья при поездке за рубеж. Страховые риски могут включать покрытие по пакету от несчастного случая, медицинские расходы, в т. ч. стоматологии, хирургии, медицинская эвакуация, компенсация похорон, репатриация останков, чрезвычайные гостиничные расходы, поездка замены бизнес коллеги, экстренный вызов члена семьи, залог для освобождения из тюрьмы, задержка и потеря багажа, задержка рейса, нападение.

Страхование ВЗР может быть двух типов:
- сервисная страховка: страховая сама оплачивает все необходимые расходы;
- компенсационная страховка: вы оплачиваете счета сами, после чего страховая компенсирует расходы.

** Действия в чрезвычайной ситуации
1. позвонить в ассистанс и следовать всем инструкциям;
2. согласовать все действия с ассистансом.

* Виды мошенничества в путешествиях
Опасайтесь незнакомцев, которые сталкиваются с вами на тротуаре или случайно проливают на вас напиток на переполненной людьми площади. Обращайте внимание на мотоциклистов и парней на мотороллерах.

* Правила поведения в мультикультурной среде
В любом государстве мира желательно:
- проявлять дружелюбие к местному населению, считаться с его образом жизни;
- строго соблюдать законодательство страны прибывания;
- избегать поездок по неблагополучным районам;
- не вступать в конфликты;
- не махать на человека рукой;
- уважать традиции и обычаи;
- не проявлять высокомерия и пренебрежения к местной культуре;
- не допускать оскорбительных высказываний по отношению к руководителям страны;
- не вступать в конфликт с представителями правоохранительных органов;
- не использовать оскорбительные жесты;
- не употреблять ненормативную лексику;
- не критиковать местную кухню в присутствии местного населения;
- учитывать специфику чаевых в стране пребывания;
- не злоупотреблять алкоголем;
- соблюдать ПДД и быть вежливым за рулем;
- соблюдать минимальную дистанцию в 50-60 см от собеседника;
- не допускать фамильярного отношения;
- иметь при себе документы, удостоверяющие личность;
- осмотрительно вести фотосъемку.

В странах с исламскими традициями не следует:
- обращать пристальные взгляды на женщин;
- задавать вопросы иностранному собеседнику и его супруге;
- пытаться познакомиться с женской частью семьи хозяина дома;
- приглашать женскую часть семьи за общий стол;
- протягивать женщине руки при знакомстве;
- заходить в отделение общественного транспорта, предназначенного для лиц другого пола;
- проявлять назойливое внимание к молящимся людям;
- употреблять спиртные напитки в общественных местах;
- предлагать местным жителям алкоголь и изделия из свиной кожи в качестве подарка;
- заказывать и предлагать блюда из свинины;
- принимать пищу, воду, курить в общественных местах во время рамадана;
- брать и предлагать пищу левой рукой;
- пристально глядеть на человека, принимающего пищу;
- входить в жилое помещение в уличной обуви;
- находиться на пляже без купального костюма;
- участвовать в азартных играх;
- допускать прилюдные объятия или поцелуи.

В странах с буддийскими традициями не следует:
- посещать религиозно-культурные объекты в обуви и чрезмерно открытой одежде;
- фотографироваться в копирующих позах будды на ее фоне;
- дотрагиваться до головы местных жителей.

* Подготовка к путешествию
План подготовки к путешествию:
1. климат;
2. одежда в зависимости от пола;
3. особенности поведения;
4. наличные деньги.

Следует взять с собой:
- документы, удостоверяющие личность;
- страховые и медицинские полисы;
- копии всех необходимых документов;
- аптечка;
- карты и путеводители.

Не забыть перед поездкой:
- установить нужные приложения на смартфон;
- узнать правила поведения в стране;
- разделить деньги и документы на части;
- сделать прививки.
