* Классификация ЧС
** Основные определения
Чрезвычайная ситуация (ЧС) — это обстановка, образующаяся в результате стихийных бедствий, производственных аварий и других катастроф. Характеризуется существенным нарушением нормальной жизнедеятельности населения, функционирования объектов экономики, общественной жизни и природной среды.

Источник ЧС — опасное природное явление, авария, широко распространенная инфекционная болезнь людей, сельскохозяйственных животных и растений, а также применение современных средств поражения, в результате чего произошла или может возникнуть ЧС.

Авария — это опасное техногенное происшествие, создающее на объекте определенной территории или акватории угрозу жизни и здоровью людей, приводящее к разрушению зданий, сооружений, оборудования и транспортных средств, нарушению транспортного и производственного процесса, а также нанесение ущерба окружающей природной среде.

Катастрофа — это крупная авария, как правило, с многочисленными человеческими жертвами, значительным материальным ущербом и другими тяжелыми последствиями.

Очаг поражения — это территория с расположенной на ней населением, животными, зданиями и сооружениями, инженерными сетями и коммуникациями, на которую воздействует опасные вредные факторы ЧС.

Каждое ЧС имеет свою физическую сущность, свои, только ей присущие причины возникновения, движущие силы, характер возникновения, свои особенности воздействия на человека и среду обитания. Исходя из этого, все ЧС могут быть классифицированы по разным признакам.

** Классификация по природе происхождения
*Стихийные бедствия* — это опасные природные явления или процессы, имеющие чрезвычайный характер и приводящие к нарушению повседневного уклада жизни более или менее значительных групп населения, человеческим жертвам, уничтожению материальных ценностей. Примеры стихийных бедствий:
- землетрясения;
- наводнения;
- цунами;
- извержение вулканов;
- оползни;
- селевые потоки;
- ураганы;
- снежные заносы;
- засухи;
- длительные проливные дожди;
- сильные устойчивые морозы;
- массовое распространение вредителей сельского и лесного хозяйства.

*Техногенные катастрофы* — это внезапный выход из строй машин, механизмов и агрегатов во время их эксплуатации, сопровождающееся серьезным нарушением производственного процесса, взрывами, образованием очагов, пожаров, радиоактивным, химическим или биологическим заражением местности, групповым поражением людей, аварией на промышленных объектах, строительстве, железнодорожном, воздушном, трубопроводном транспорте и т. д.

*Антропогенные катастрофы* — это качественное изменение биосферы, вызванное действием антропогенных факторов, порождаемых деятельностью человека и оказывающее вредное влияние на людей, животных и растительный мир, окружающую среду в целом.

*Социально-политические конфликты* — это крайне острая форма разрешения противоречий между государствами с применением современных средств поражения, а также межнациональные кризисы, сопровождающиеся насилием.

** Классификация по скорости распространения опасности
*Внезапные* — землетрясения, взрывы, транспортные аварии и т. д.

*Стремительные* — пожары, гидродинамические аварии с образованием волны прорыва, аварии с выбросом ядовитых веществ.

*Умеренные* — паводковые наводнения, извержения вулканов, аварии с выбросом радиоактивных веществ.

*Плавные* — с медленно распространяющейся опасностью, засухи, эпидемии, загрязнения почвы.

** Классификация по масштабам поражения
*Локальные* — последствия ограничиваются пределами объекта экономики и могут быть устранены за счет его сил и ресурсов.

*Местные* — имеют масштабы распространения в пределах населенных пунктов, в т. ч. крупного города, административного района и могут быть устранены за счет сил и ресурсов области.

*Региональные* — ограничиваются пределами нескольких областей или экономического района.

*Национальные* — имеют последствия, охватывающие несколько экономических районов, но не выходящие за пределы страны.

*Глобальные* — выходят за пределы страны и затрагивают другие государства.

* Химически опасные объекты
*Химически опасный объект* — объект, на котором хранят, перерабатывают, используют или перемещают опасные химические вещества, при аварии на котором или при разрушении которого может произойти гибель или химическое заражение людей, сельскохозяйственных животных, растений, а также окружающей среды аварийно опасными химическими веществами.

К химически опасным объектам относятся:
- предприятия химического и нефтехимического комплекса;
- хладокомбинаты, мясокомбинаты, молокозаводы;
- станции водоочистки городов;
- газопроводы, нефтепроводы, аммиакопроводы;
- различные хранилища опасных веществ.

В основе классификации химически опасных веществ лежит количественная оценка степени опасности объекта с учетом следующих характеристик:
- масштабы возможной химической аварии для населения и прилегающих к объекту территорий;
- типы возможных ЧС при аварии на химически опасном объекте по наихудшему сценарию;
- степени опасности химических веществ, используемых на химически опасном объекте;
- риск возникновения аварии на химически опасном объекте.

По масштабам возможных последствий химической аварии выделяют следующие степени опасности:
- 1-й степени: крупные предприятия химической промышленности, водоочистные сооружения;
- 2-й степени: промышленные предприятия, предприятия химической, нефтехимической, пищевой и перерабатывающей промышленности, водоочистные сооружения крупных городов, железнодорожные узлы;
- 3-й степени: небольшие предприятия пищевой и перерабатывающей промышленности, хладокомбинаты, мясокомбинаты;
- 4-й степени: предприятия с малым количеством химически опасных веществ (менее 1 тонны).

Аварийно химически опасное вещество — это химическое вещество, применяемое в промышленности и сельском хозяйстве при аварийном выбросе, розливе которого может произойти заражение окружающей среды в поражающей живые организмы концентрациях, токсодозах. Важнейшим свойством является токсичность, под которой понимается их ядовитость, характеризуемая смертельной, поражающей и пороговой концентрациями.

Токсодоза — показатель, характеризующий количество токсичного вещества, поглощенного организмом за определенный интервал времени.


# https://ria.ru/20190325/1552026366.html
# http://www.consultant.ru/document/cons_doc_LAW_78699/4de678111a05779d37d8b56311e6cab3d12e396f/
# https://70.mchs.gov.ru/deyatelnost/rekomendacii-naseleniyu/pozharnaya-bezopasnost/deystviya-pri-pozhare/eto-vazhno-znat
